# Generated by Django 6.0.7 on 2026-08-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name="Цена"),
        ),
    ]
